spring:
  application:
    name: chef
  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USERNAME}
    password: ${DB_TEST_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true