spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB    # Maximum file size allowed
      max-request-size: 10MB # Maximum request size allowed
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8083/realms/Yolo  ${JwtIssuerURI}
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs ${JwtSetURI}
           issuer-uri: ${JwtIssuerURI}
           jwk-set-uri: ${JwtSetURI}
  application:
    name: chef
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
api:
  key:
    ${ApiKey}
  GeminiUrl:
    ${GeminiUrl}
server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: yolo-chef
      principle-attribute: preferred_username
